title Single Immediate Domestic, Happy Path

participant PSU
participant PISP
participant ASPSP Resource Server
participant ASPSP Authentication Server


note over PSU, ASPSP Authentication Server: Setup Single Immediate Payment
PSU -> PISP: Checkout
note over PISP, ASPSP Resource Server: Idempotency-Key: PISP-guid-1
PISP -> ASPSP Resource Server: POST /payments
note right of ASPSP Resource Server: validates and stores payment setup payload
ASPSP Resource Server --> PISP: HTTP 201 Created { PaymentId }

opt: PISP can optionally retrieve payment setup resource
note over PSU, ASPSP Authentication Server: Get Payment Setup Resource (includes status)
PISP --> ASPSP Resource Server: GET /payments/${PaymentId}
ASPSP Resource Server --> PISP: HTTP 200 OK
end

PISP -> PSU: Redirect PSU to ASPSP for Auth

note over PSU, ASPSP Authentication Server: Authorise Payment - OAuth 2.0 Flow
PSU -> ASPSP Authentication Server: Sign-in to ASPSP web/mobile app
ASPSP Authentication Server --> PSU: View payment details
PSU -> ASPSP Authentication Server: Authorise consent for single payment
ASPSP Authentication Server --> PSU: Redirect plus auth code
PSU -> PISP: Redirect auth code
PISP -> ASPSP Resource Server: /token
ASPSP Resource Server --> PISP: access token


note over PSU, ASPSP Authentication Server: Submit Single Payment
PISP -> ASPSP Resource Server: POST /payment-submissions   { PaymentId, .. }
note right of ASPSP Resource Server: Validate payment submission against payment setup payload
ASPSP Resource Server --> PISP: HTTP 201 Created { PaymentSubmissionId }
opt PISP can optionally retrieve payment submission resource
note over PSU, ASPSP Authentication Server: Get Payment Submission Resource (includes status)
PISP --> ASPSP Resource Server: GET /payment-submissions/${PaymentSubmissionId}
ASPSP Resource Server --> PISP: HTTP 200 OK
opt Async status webhook [TO BE DEFINED]
ASPSP Resource Server --> PISP: POST /PISP_notifications_url
PISP --> ASPSP Resource Server: 200 OK
end
end
