title Single Immediate Domestic

participant PSU
participant TPP
participant ASPSP Resource Server
participant ASPSP Authentication Server


note over PSU, ASPSP Authentication Server: Setup Single Payment
PSU -> TPP: Checkout
TPP -> ASPSP Resource Server: POST /payments
ASPSP Resource Server --> TPP: PaymentAuthorisationID (200,4xx, 5xx)
TPP -> PSU: Redirect PSU to ASPSP for Auth


note over PSU, ASPSP Authentication Server: Authorise Payment - OAuth 2.0 Flow
PSU -> ASPSP Authentication Server: Sign-in to ASPSP web/mobile app
ASPSP Authentication Server --> PSU: View payment details
PSU -> ASPSP Authentication Server: Authorise consent for single payment
ASPSP Authentication Server --> PSU: Redirect plus auth code
PSU -> TPP: Redirect auth code
TPP -> ASPSP Resource Server: /token
ASPSP Resource Server --> TPP: access token


note over PSU, ASPSP Authentication Server: Submit Single Payment
TPP -> ASPSP Resource Server: PATCH /payments/${PaymentAuthorisationID}
ASPSP Resource Server --> TPP: HTTP 200, 202, 4xx, 5xx
note over PSU, ASPSP Authentication Server: Get Payment Status
TPP --> ASPSP Resource Server: GET /payments/${PaymentAuthorisationID}/status
ASPSP Resource Server --> TPP: HTTP 200

opt
ASPSP Resource Server --> TPP: Async status webhook
end
