title Single Immediate Domestic

participant PSU
participant TPP
participant ASPSP Resource Server
participant ASPSP Authentication Server


opt Setup Single Payment
    PSU -> TPP: Checkout
    TPP -> ASPSP Resource Server: /payments
    ASPSP Resource Server --> TPP: PaymentAuthorisationID, EndToEndIdentification (200,4xx, 5xx)
    TPP -> PSU: Redirect PSU to ASPSP for Auth
end

opt Authorise Payment
 note over PSU, ASPSP Authentication Server: include OAuth 2.0 params (scope etc) and IntentID
 PSU -> ASPSP Authentication Server: Sign-in to ASPSP web/mobile app
 ASPSP Authentication Server --> PSU: View payment details
 PSU -> ASPSP Authentication Server: Authorise consent for single payment
 ASPSP Authentication Server --> PSU: Redirect plus auth code
end

opt Execute Single Payment
    PSU -> TPP: Redirect auth code
    TPP -> ASPSP Resource Server: /token
    ASPSP Resource Server --> TPP: access token
    TPP -> ASPSP Resource Server: /payments/${IntentID}/execute
    ASPSP Resource Server --> TPP: HTTP 200, 202, 4xx, 5xx
    ASPSP Resource Server --> TPP: Async status webhook (optional)
end
